AWS1:
	sudo python GameControls.py -e a2w3x76c5t3np8.iot.us-west-2.amazonaws.com -r root-CA.crt -C us-west-2:1e1899db-7186-4aa1-9fd5-aa74e4792abb -id ECEM119Pi -t ECEM119 
AWS2:
	sudo python GameControls.py -e a2w3x76c5t3np8.iot.us-west-2.amazonaws.com -r root-CA.crt -C us-west-2:6a847a06-5a13-4ea8-a04d-d6b1bc24a032 -id ECEM119Pi2 -t ECEM119 
AWS3:	
	sudo python GameControls.py -e a2w3x76c5t3np8.iot.us-west-2.amazonaws.com -r root-CA.crt -C us-west-2:1e1899db-7186-4aa1-9fd5-aa74e4792abb -id ECEM119Pi2 -t ECEM119 
AWS4:
	sudo python GameControls.py -e a2w3x76c5t3np8.iot.us-west-2.amazonaws.com -r root-CA.crt -C us-west-2:6a847a06-5a13-4ea8-a04d-d6b1bc24a032 -id ECEM119Pi -t ECEM119 
